# Generated by Django 3.0.3 on 2020-04-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200407_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
