# Generated by Django 3.0.3 on 2020-04-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
    ]
